import { User, Event, Buddy, Message, Conversation, GroupChat, Sport, Goal, GroupMember } from '@/types';

// Mock Sports
export const mockSports: Sport[] = [
  { id: 1, name: 'Running', icon: '🏃' },
  { id: 2, name: 'Cycling', icon: '🚴' },
  { id: 3, name: 'Swimming', icon: '🏊' },
  { id: 4, name: 'Yoga', icon: '🧘' },
  { id: 5, name: 'Basketball', icon: '🏀' },
  { id: 6, name: 'Tennis', icon: '🎾' },
  { id: 7, name: 'Weightlifting', icon: '🏋️' },
  { id: 8, name: 'Hiking', icon: '🥾' },
];

// Mock Goals
export const mockGoals: Goal[] = [
  { id: 1, name: 'Lose Weight', description: 'Achieve your weight loss goals' },
  { id: 2, name: 'Build Muscle', description: 'Gain strength and muscle mass' },
  { id: 3, name: 'Improve Endurance', description: 'Build cardiovascular fitness' },
  { id: 4, name: 'Stay Active', description: 'Maintain an active lifestyle' },
  { id: 5, name: 'Train for Competition', description: 'Prepare for athletic competitions' },
];

// Mock Users (50+ users)
export const mockUsers: User[] = [
  {
    id: 1,
    email: 'alice@example.com',
    full_name: 'Alice Johnson',
    age: 28,
    location: 'San Francisco, CA',
    bio: 'Love running and yoga! Looking for workout buddies to stay motivated.',
    avatar_url: 'https://picsum.photos/seed/100/400/600',
    created_at: new Date().toISOString(),
    updated_at: null,
    sports: [mockSports[0], mockSports[3]],
    goals: [mockGoals[2], mockGoals[3]],
  },
  {
    id: 2,
    email: 'bob@example.com',
    full_name: 'Bob Smith',
    age: 32,
    location: 'San Francisco, CA',
    bio: 'Cycling enthusiast and weekend warrior!',
    avatar_url: 'https://picsum.photos/seed/101/400/600',
    created_at: new Date().toISOString(),
    updated_at: null,
    sports: [mockSports[1]],
    goals: [mockGoals[3]],
  },
  {
    id: 3,
    email: 'charlie@example.com',
    full_name: 'Charlie Brown',
    age: 25,
    location: 'Oakland, CA',
    bio: 'Weightlifting and CrossFit enthusiast.',
    avatar_url: 'https://picsum.photos/seed/102/400/600',
    created_at: new Date().toISOString(),
    updated_at: null,
    sports: [mockSports[6]],
    goals: [mockGoals[1]],
  },
  {
    id: 4,
    email: 'diana@example.com',
    full_name: 'Diana Prince',
    age: 30,
    location: 'San Francisco, CA',
    bio: 'Yoga and Pilates instructor.',
    avatar_url: 'https://picsum.photos/seed/103/400/600',
    created_at: new Date().toISOString(),
    updated_at: null,
    sports: [mockSports[3]],
    goals: [mockGoals[3]],
  },
  {
    id: 5,
    email: 'eve@example.com',
    full_name: 'Eve Martinez',
    age: 27,
    location: 'Berkeley, CA',
    bio: 'Swimmer and triathlete.',
    avatar_url: 'https://picsum.photos/seed/104/400/600',
    created_at: new Date().toISOString(),
    updated_at: null,
    sports: [mockSports[2]],
    goals: [mockGoals[4]],
  },
  {
    id: 6,
    email: 'frank@example.com',
    full_name: 'Frank Wilson',
    age: 35,
    location: 'San Francisco, CA',
    bio: 'Basketball player and coach.',
    avatar_url: 'https://picsum.photos/seed/105/400/600',
    created_at: new Date().toISOString(),
    updated_at: null,
    sports: [mockSports[4]],
    goals: [mockGoals[3]],
  },
  {
    id: 7,
    email: 'grace@example.com',
    full_name: 'Grace Lee',
    age: 29,
    location: 'Oakland, CA',
    bio: 'Tennis player and fitness enthusiast.',
    avatar_url: 'https://picsum.photos/seed/106/400/600',
    created_at: new Date().toISOString(),
    updated_at: null,
    sports: [mockSports[5]],
    goals: [mockGoals[4]],
  },
  {
    id: 8,
    email: 'henry@example.com',
    full_name: 'Henry Davis',
    age: 31,
    location: 'San Francisco, CA',
    bio: 'Hiking and outdoor adventure enthusiast.',
    avatar_url: 'https://picsum.photos/seed/107/400/600',
    created_at: new Date().toISOString(),
    updated_at: null,
    sports: [mockSports[7]],
    goals: [mockGoals[2]],
  },
  {
    id: 9,
    email: 'ivy@example.com',
    full_name: 'Ivy Chen',
    age: 26,
    location: 'Berkeley, CA',
    bio: 'Marathon runner training for Boston.',
    avatar_url: 'https://picsum.photos/seed/108/400/600',
    created_at: new Date().toISOString(),
    updated_at: null,
    sports: [mockSports[0]],
    goals: [mockGoals[4]],
  },
  {
    id: 10,
    email: 'jack@example.com',
    full_name: 'Jack Taylor',
    age: 33,
    location: 'San Francisco, CA',
    bio: 'Cyclist and mountain biker.',
    avatar_url: 'https://picsum.photos/seed/109/400/600',
    created_at: new Date().toISOString(),
    updated_at: null,
    sports: [mockSports[1]],
    goals: [mockGoals[2]],
  },
  // Add more users
  ...Array.from({ length: 40 }, (_, i) => ({
    id: 11 + i,
    email: `user${11 + i}@example.com`,
    full_name: `User ${11 + i}`,
    age: 20 + (i % 20),
    location: ['San Francisco, CA', 'Oakland, CA', 'Berkeley, CA', 'Fremont, CA'][i % 4],
    bio: `Fitness enthusiast ${11 + i}`,
    avatar_url: `https://picsum.photos/seed/${110 + i}/400/600`,
    created_at: new Date().toISOString(),
    updated_at: null,
    sports: mockSports.slice(0, 2 + (i % 3)),
    goals: mockGoals.slice(0, 1 + (i % 2)),
  })),
];

// Current user (Alice)
export const currentUser: User = mockUsers[0];

// Mock Events
const now = new Date();
export const mockEvents: Event[] = [
  {
    id: 1,
    title: 'Morning Run in Golden Gate Park',
    description: 'Join us for a scenic 5K run through Golden Gate Park. All paces welcome!',
    sport_id: 1,
    host_id: 1,
    location: 'Golden Gate Park, San Francisco',
    start_time: new Date(now.getTime() + 24 * 60 * 60 * 1000).toISOString(),
    end_time: new Date(now.getTime() + 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    max_participants: 20,
    is_cancelled: false,
    image_url: 'https://picsum.photos/seed/event1/800/600',
    created_at: new Date().toISOString(),
    updated_at: null,
    participant_count: 8,
    sport: mockSports[0],
    host: mockUsers[0],
    participants: mockUsers.slice(0, 8),
  },
  {
    id: 2,
    title: 'Cycling Group Ride - Marin County',
    description: 'Long ride through Marin County. Intermediate to advanced riders.',
    sport_id: 2,
    host_id: 2,
    location: 'Sausalito, CA',
    start_time: new Date(now.getTime() + 48 * 60 * 60 * 1000).toISOString(),
    end_time: new Date(now.getTime() + 48 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
    max_participants: 15,
    is_cancelled: false,
    image_url: 'https://picsum.photos/seed/event2/800/600',
    created_at: new Date().toISOString(),
    updated_at: null,
    participant_count: 5,
    sport: mockSports[1],
    host: mockUsers[1],
    participants: mockUsers.slice(1, 6),
  },
  {
    id: 3,
    title: 'Yoga in the Park',
    description: 'Outdoor yoga session in Dolores Park. Bring your mat!',
    sport_id: 4,
    host_id: 4,
    location: 'Dolores Park, San Francisco',
    start_time: new Date(now.getTime() + 72 * 60 * 60 * 1000).toISOString(),
    end_time: new Date(now.getTime() + 72 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
    max_participants: 30,
    is_cancelled: false,
    image_url: 'https://picsum.photos/seed/event3/800/600',
    created_at: new Date().toISOString(),
    updated_at: null,
    participant_count: 12,
    sport: mockSports[3],
    host: mockUsers[3],
    participants: mockUsers.slice(0, 12),
  },
  {
    id: 4,
    title: 'Basketball Pickup Game',
    description: 'Casual pickup basketball game. All skill levels welcome!',
    sport_id: 5,
    host_id: 6,
    location: 'Mission Bay, San Francisco',
    start_time: new Date(now.getTime() + 96 * 60 * 60 * 1000).toISOString(),
    end_time: new Date(now.getTime() + 96 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    max_participants: 10,
    is_cancelled: false,
    image_url: 'https://picsum.photos/seed/event4/800/600',
    created_at: new Date().toISOString(),
    updated_at: null,
    participant_count: 6,
    sport: mockSports[4],
    host: mockUsers[5],
    participants: mockUsers.slice(2, 8),
  },
  {
    id: 5,
    title: 'Swimming Session at Aquatic Park',
    description: 'Open water swimming practice. Safety first!',
    sport_id: 3,
    host_id: 5,
    location: 'Aquatic Park, San Francisco',
    start_time: new Date(now.getTime() + 120 * 60 * 60 * 1000).toISOString(),
    end_time: new Date(now.getTime() + 120 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
    max_participants: 12,
    is_cancelled: false,
    image_url: 'https://picsum.photos/seed/event5/800/600',
    created_at: new Date().toISOString(),
    updated_at: null,
    participant_count: 4,
    sport: mockSports[2],
    host: mockUsers[4],
    participants: mockUsers.slice(3, 7),
  },
  {
    id: 6,
    title: 'Hiking Mission Peak',
    description: 'Challenging hike up Mission Peak. Bring water and snacks!',
    sport_id: 8,
    host_id: 8,
    location: 'Mission Peak, Fremont',
    start_time: new Date(now.getTime() + 144 * 60 * 60 * 1000).toISOString(),
    end_time: new Date(now.getTime() + 144 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
    max_participants: 15,
    is_cancelled: false,
    image_url: 'https://picsum.photos/seed/event6/800/600',
    created_at: new Date().toISOString(),
    updated_at: null,
    participant_count: 7,
    sport: mockSports[7],
    host: mockUsers[7],
    participants: mockUsers.slice(4, 11),
  },
];

// Mock Buddies (accepted buddies for current user)
export const mockBuddies: Buddy[] = [
  {
    id: 1,
    user1_id: 1,
    user2_id: 2,
    match_score: 85,
    status: 'accepted',
    created_at: new Date().toISOString(),
    user1: currentUser,
    user2: mockUsers[1],
  },
  {
    id: 2,
    user1_id: 1,
    user2_id: 3,
    match_score: 78,
    status: 'accepted',
    created_at: new Date().toISOString(),
    user1: currentUser,
    user2: mockUsers[2],
  },
  {
    id: 3,
    user1_id: 1,
    user2_id: 4,
    match_score: 92,
    status: 'accepted',
    created_at: new Date().toISOString(),
    user1: currentUser,
    user2: mockUsers[3],
  },
];

// Mock Suggested Buddies (for discovery)
export const mockSuggestedBuddies: any[] = mockUsers.slice(5, 25).map((user, index) => ({
  user,
  match_score: 60 + (index % 30),
  recent_events: mockEvents.slice(0, 2),
  badges: ['🏃 Runner', '💪 Active', '⭐ Top Rated'].slice(0, 1 + (index % 3)),
  photos: [
    `https://picsum.photos/seed/${user.id}photo1/400/600`,
    `https://picsum.photos/seed/${user.id}photo2/400/600`,
    `https://picsum.photos/seed/${user.id}photo3/400/600`,
  ],
}));

// Mock Group Chats
export const mockGroupChats: GroupChat[] = [
  {
    id: 1,
    name: 'Bay Area Runners',
    description: 'A group for Bay Area runners to connect and plan workouts!',
    avatar_url: 'https://picsum.photos/seed/group1/400/400',
    created_by_id: 1,
    created_at: new Date().toISOString(),
    updated_at: null,
    members: [
      { id: 1, full_name: 'Alice Johnson', avatar_url: mockUsers[0].avatar_url, is_admin: true },
      { id: 2, full_name: 'Bob Smith', avatar_url: mockUsers[1].avatar_url, is_admin: false },
      { id: 3, full_name: 'Charlie Brown', avatar_url: mockUsers[2].avatar_url, is_admin: false },
      { id: 4, full_name: 'Diana Prince', avatar_url: mockUsers[3].avatar_url, is_admin: false },
    ],
    created_by: { id: 1, full_name: 'Alice Johnson', avatar_url: mockUsers[0].avatar_url, is_admin: true },
  },
  {
    id: 2,
    name: 'Weekend Warriors',
    description: 'Weekend workout group for all fitness levels!',
    avatar_url: 'https://picsum.photos/seed/group2/400/400',
    created_by_id: 2,
    created_at: new Date().toISOString(),
    updated_at: null,
    members: [
      { id: 2, full_name: 'Bob Smith', avatar_url: mockUsers[1].avatar_url, is_admin: true },
      { id: 1, full_name: 'Alice Johnson', avatar_url: mockUsers[0].avatar_url, is_admin: false },
      { id: 5, full_name: 'Eve Martinez', avatar_url: mockUsers[4].avatar_url, is_admin: false },
    ],
    created_by: { id: 2, full_name: 'Bob Smith', avatar_url: mockUsers[1].avatar_url, is_admin: true },
  },
  {
    id: 3,
    name: 'Yoga Enthusiasts',
    description: 'Yoga and mindfulness group!',
    avatar_url: 'https://picsum.photos/seed/group3/400/400',
    created_by_id: 4,
    created_at: new Date().toISOString(),
    updated_at: null,
    members: [
      { id: 4, full_name: 'Diana Prince', avatar_url: mockUsers[3].avatar_url, is_admin: true },
      { id: 1, full_name: 'Alice Johnson', avatar_url: mockUsers[0].avatar_url, is_admin: false },
    ],
    created_by: { id: 4, full_name: 'Diana Prince', avatar_url: mockUsers[3].avatar_url, is_admin: true },
  },
];

// Mock Messages
const messageTemplates = [
  'Hey! Are you still up for that run tomorrow?',
  'Thanks for the match! Would love to work out together sometime.',
  'Saw you\'re into running, want to join our group session?',
  'Hey! How\'s your training going?',
  'Are you going to the Morning Run event?',
  'Would you be interested in a workout session this weekend?',
  'Hey! I noticed we have similar fitness goals. Want to connect?',
  'Thanks for accepting my match! Let\'s plan something!',
  'Hi there! Your profile caught my eye. What\'s your favorite workout?',
  'Excited for Morning Run in Golden Gate Park!',
  'See you all at Golden Gate Park!',
  'What time should we meet?',
  'Can\'t wait! This is going to be great.',
  'Anyone need a ride?',
  'Hey everyone! Who\'s up for a workout this weekend?',
  'Great session today! Thanks everyone for coming.',
  'Looking forward to our next group activity!',
];

export const mockMessages: Message[] = [
  // 1:1 messages
  {
    id: 1,
    sender_id: 2,
    receiver_id: 1,
    event_id: null,
    group_id: null,
    content: messageTemplates[0],
    is_read: false,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    sender: mockUsers[1],
    receiver: currentUser,
  },
  {
    id: 2,
    sender_id: 1,
    receiver_id: 2,
    event_id: null,
    group_id: null,
    content: messageTemplates[4],
    is_read: true,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    sender: currentUser,
    receiver: mockUsers[1],
  },
  {
    id: 3,
    sender_id: 3,
    receiver_id: 1,
    event_id: null,
    group_id: null,
    content: messageTemplates[1],
    is_read: false,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    sender: mockUsers[2],
    receiver: currentUser,
  },
  {
    id: 4,
    sender_id: 4,
    receiver_id: 1,
    event_id: null,
    group_id: null,
    content: messageTemplates[2],
    is_read: true,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    sender: mockUsers[3],
    receiver: currentUser,
  },
  // Event messages
  {
    id: 5,
    sender_id: 2,
    receiver_id: null,
    event_id: 1,
    group_id: null,
    content: messageTemplates[9],
    is_read: false,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    sender: mockUsers[1],
    event: mockEvents[0],
  },
  {
    id: 6,
    sender_id: 3,
    receiver_id: null,
    event_id: 1,
    group_id: null,
    content: messageTemplates[10],
    is_read: false,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    sender: mockUsers[2],
    event: mockEvents[0],
  },
  // Group messages
  {
    id: 7,
    sender_id: 2,
    receiver_id: null,
    event_id: null,
    group_id: 1,
    content: messageTemplates[14],
    is_read: false,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    sender: mockUsers[1],
  },
  {
    id: 8,
    sender_id: 1,
    receiver_id: null,
    event_id: null,
    group_id: 1,
    content: messageTemplates[15],
    is_read: false,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    sender: currentUser,
  },
];

// Mock Conversations
export const mockConversations: Conversation[] = [
  {
    type: 'user',
    id: 2,
    name: mockUsers[1].full_name || 'Bob Smith',
    avatar_url: mockUsers[1].avatar_url,
    last_message: {
      content: messageTemplates[4],
      created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    },
    unread_count: 1,
  },
  {
    type: 'user',
    id: 3,
    name: mockUsers[2].full_name || 'Charlie Brown',
    avatar_url: mockUsers[2].avatar_url,
    last_message: {
      content: messageTemplates[1],
      created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    },
    unread_count: 1,
  },
  {
    type: 'user',
    id: 4,
    name: mockUsers[3].full_name || 'Diana Prince',
    avatar_url: mockUsers[3].avatar_url,
    last_message: {
      content: messageTemplates[2],
      created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    },
    unread_count: 0,
  },
  {
    type: 'event',
    id: 1,
    name: mockEvents[0].title,
    avatar_url: mockEvents[0].image_url,
    last_message: {
      content: messageTemplates[10],
      created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    unread_count: 2,
  },
  {
    type: 'group',
    id: 1,
    name: mockGroupChats[0].name,
    avatar_url: mockGroupChats[0].avatar_url,
    member_count: mockGroupChats[0].members?.length || 4,
    last_message: {
      content: messageTemplates[15],
      created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    },
    unread_count: 1,
  },
  {
    type: 'group',
    id: 2,
    name: mockGroupChats[1].name,
    avatar_url: mockGroupChats[1].avatar_url,
    member_count: mockGroupChats[1].members?.length || 3,
    last_message: {
      content: messageTemplates[14],
      created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    unread_count: 0,
  },
];

